[project]
name = "intelligentbookapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Supreme_Engineer98", email = "gmavropouloscoding@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "alembic>=1.16.5",
    "asyncpg>=0.31.0",
    "fastapi>=0.128.8",
    "greenlet==3.1.1",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.39.0",
]

[project.scripts]
intelligentbookapi = "intelligentbookapi:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "alembic",
]
